### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by tylermcrobert** [pdelfan/arena-typed#3]
Hi there, I am getting the following error when importing the package:

```
Module '"arena-typed"' has no exported member 'Arena'. Did you mean to use 'import Arena from "arena-typed"' instead?ts(2614)
```

I am at the latest version (1.0.4)

**Comment by pdelfan** [comment]
Hi @tylermcrobert, thanks for letting me know. The example on the documentation is using a named import from the older version. If you try a default import `import Arena from 'arena-typed'`, it should work. I've updated the documentation to reflect this change. Let me know if this works!

**Comment by pdelfan** [comment]
> Hi @tylermcrobert, thanks for letting me know. The example on the documentation is using a named import from the older version. If you try a default import `import Arena from 'arena-typed'`, it should work. I've updated the documentation to reflect this change. Let me know if this works!

Hi @tylermcrobert, could you please confirm if this fixes the error?

**Comment by tylermcrobert** [comment]
Hey @pdelfan, apologies for the delay. I'm now getting the following: 

`const arena = new Arena("<token>");`

`TypeError: __vite_ssr_import_0__.default is not a constructor
    at load (/Users/tylermcrobert/Sites/are.na-screenshotter/web/src/routes/+page.server.ts:4:16)
    at Module.load_server_data (/Users/tylermcrobert/Sites/are.na-screenshotter/web/node_modules/.pnpm/@sveltejs+kit@2.5.10_@sveltejs+vite-plugin-svelte@3.1.0_svelte@5.0.0-next.142_vite@5.2.11/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:61:41)`

**Comment by pdelfan** [comment]
Hey @tylermcrobert, sorry for an even longer delay and thanks for helping me out. Unfortunately I'm at a max capacity and don't have enough time to work on the API, but I do plan to get back to it sometime in future.
